Repository fasten-project/fasten, pull requests merged in 2020-09, with the labels that each got.

#70 Refactor constants
  analyzer/graph-plugin/src/main/java/eu/fasten/analyzer/graphplugin/GraphDatabasePlugin.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraph.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraphTest.java
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePlugin.java
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePluginTest.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPlugin.java
  core/src/main/java/eu/fasten/core/data/Constants.java
  server/src/main/java/eu/fasten/server/connectors/PostgresConnector.java
Labels: Priority: Low, maintenance

#21 RestAPI
  analyzer/README.md
  analyzer/pom.xml
  analyzer/restapi-plugin/README.md
  analyzer/restapi-plugin/pom.xml
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/Main.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/RestAPIPlugin.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/server/OpenAPIServer.java
  analyzer/restapi-plugin/src/main/resources/openapispec.json
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: enhancement

#78 Added analysis phase to the License and Compliance plugin
  analyzer/compliance-analyzer/README.md
  analyzer/compliance-analyzer/dummyKafkaTopic.json
  analyzer/compliance-analyzer/src/main/java/eu/fasten/analyzer/complianceanalyzer/ComplianceAnalyzerPlugin.java
  analyzer/compliance-analyzer/src/main/resources/docker/job.yaml
  analyzer/compliance-analyzer/src/main/resources/docker/master-config.yaml
  analyzer/compliance-analyzer/src/main/resources/docker/service.yaml
Labels: enhancement

#76 Extracted Metadata fields + Parent coordinate extraction in POMAnalyzer
  analyzer/metadata-plugin/pom.xml
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePlugin.java
  analyzer/metadata-plugin/src/main/resources/metadata_db_init.sql
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePluginTest.java
  analyzer/pom-analyzer/pom.xml
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractorTest.java
  core/src/main/java/eu/fasten/core/data/graphdb/GidGraph.java
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/Public.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/UDTs.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/enums/ReceiverType.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/tables/Callables.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/tables/Edges.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/tables/records/CallablesRecord.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/tables/records/EdgesRecord.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/udt/Receiver.java
  core/src/main/java/eu/fasten/core/data/metadatadb/codegen/udt/records/ReceiverRecord.java
Labels: Priority: High, maintenance
