Repository fasten-project/fasten, pull requests merged in 2020-11, with the labels that each got.

#99 Added Endocode contributors
  pom.xml
Labels: Priority: Low

#73 Maven Resolver
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/Main.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/Main.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractorTest.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/utils/HgClonerTest.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/Main.java
  core/pom.xml
  core/src/main/java/eu/fasten/core/data/Constants.java
  core/src/main/java/eu/fasten/core/dbconnectors/PostgresConnector.java
  core/src/main/java/eu/fasten/core/dbconnectors/RocksDBConnector.java
  core/src/main/java/eu/fasten/core/maven/MavenResolver.java
  core/src/main/java/eu/fasten/core/maven/MavenUtilities.java
  core/src/main/java/eu/fasten/core/maven/data/Dependency.java
  core/src/main/java/eu/fasten/core/maven/data/DependencyData.java
  core/src/main/java/eu/fasten/core/maven/data/DependencyManagement.java
  core/src/main/java/eu/fasten/core/maven/data/DependencyTree.java
  core/src/test/java/eu/fasten/core/maven/MavenResolverBenchmark.java
  core/src/test/java/eu/fasten/core/maven/MavenResolverTest.java
  core/src/test/java/eu/fasten/core/maven/MavenUtilitiesTest.java
  core/src/test/java/eu/fasten/core/maven/data/DependencyDataTest.java
  core/src/test/java/eu/fasten/core/maven/data/DependencyManagementTest.java
  core/src/test/java/eu/fasten/core/maven/data/DependencyTest.java
  server/src/main/java/eu/fasten/server/FastenServer.java
Labels: Priority: High, enhancement

#81 Depedency graph
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  core/pom.xml
  core/src/main/java/eu/fasten/core/maven/DependencyGraphBuilder.java
  core/src/main/java/eu/fasten/core/maven/GraphMavenResolver.java
  core/src/main/java/eu/fasten/core/maven/MavenResolver.java
  core/src/main/java/eu/fasten/core/maven/MavenResolverBenchmark.java
  core/src/main/java/eu/fasten/core/maven/data/Dependency.java
  core/src/main/java/eu/fasten/core/maven/data/graph/DependencyEdge.java
  core/src/main/java/eu/fasten/core/maven/data/graph/DependencyNode.java
  core/src/main/java/eu/fasten/core/maven/utils/DependencyGraphUtilities.java
  core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java
  core/src/test/java/eu/fasten/core/dbconnectors/PostgresConnectorTest.java
  core/src/test/java/eu/fasten/core/maven/GraphMavenResolverTest.java
  core/src/test/java/eu/fasten/core/maven/utils/MavenUtilitiesTest.java
  server/pom.xml
Labels: Priority: High, enhancement

#104 Improving the OPAL deployment and fixing its issues
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  docker/server/Dockerfile
  server/src/main/java/eu/fasten/server/FastenServer.java
  server/src/main/java/eu/fasten/server/connectors/KafkaConnector.java
  server/src/main/java/eu/fasten/server/plugins/kafka/FastenKafkaPlugin.java
Labels: Priority: Critical

#117 DB Stitching
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/Main.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/analysis/OPALType.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/jcg/JCGTest.java
  core/src/main/java/eu/fasten/core/data/ExtendedRevisionJavaCallGraph.java
  core/src/main/java/eu/fasten/core/data/FastenJavaURI.java
  core/src/main/java/eu/fasten/core/data/FastenURI.java
  core/src/main/java/eu/fasten/core/data/JavaNode.java
  core/src/main/java/eu/fasten/core/data/JavaType.java
  core/src/main/java/eu/fasten/core/merge/CallGraphMerger.java
  core/src/main/java/eu/fasten/core/merge/CallGraphUtils.java
  core/src/main/java/eu/fasten/core/merge/DatabaseMerger.java
  core/src/main/java/eu/fasten/core/merge/LocalMerger.java
  core/src/main/java/eu/fasten/core/merge/Merger.java
  core/src/test/java/eu/fasten/core/maven/MavenResolverTest.java
  core/src/test/java/eu/fasten/core/merge/Benchmark.java
  server/src/main/java/eu/fasten/server/connectors/PostgresConnector.java
  server/src/main/java/eu/fasten/server/connectors/RocksDBConnector.java
Labels: Priority: Critical

#123 Changed REST API web framework & servlet container
  analyzer/restapi-plugin/README.md
  analyzer/restapi-plugin/pom.xml
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/Main.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/RestAPIPlugin.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/RestApplication.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/BinaryModuleApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/BinaryModuleApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/CallableApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/CallableApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/DependencyApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/DependencyApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/EdgeApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/EdgeApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/FileApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/FileApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/ModuleApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/ModuleApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/PackageApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/PackageApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/BinaryModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/CallableApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/DependencyApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/EdgeApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/FileApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/ModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/impl/PackageApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/EndpointsListener.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/KnowledgeBaseConnector.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/RestApplication.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/BinaryModuleApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/BinaryModuleApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/CallableApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/CallableApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/DependencyApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/DependencyApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/EdgeApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/EdgeApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/FileApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/FileApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/ModuleApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/ModuleApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/BinaryModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/CallableApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/DependencyApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/EdgeApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/FileApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/ModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/PackageApiServiceImpl.java
  analyzer/restapi-plugin/src/main/resources/application.properties
Labels: Priority: High, maintenance
