Repository fasten-project/fasten, pull requests merged in 2020-08, with the labels that each got.

#43 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: Type: Maintenance

#45 Improve documentation
  CONTRIBUTING.md
  README.md
  analyzer/README.md
  analyzer/graph-plugin/README.md
  analyzer/graph-plugin/src/main/java/eu/fasten/analyzer/graphplugin/GraphDatabasePlugin.java
  analyzer/graph-plugin/src/main/java/eu/fasten/analyzer/graphplugin/Main.java
  analyzer/javacg-opal/README.md
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/Main.java
  analyzer/metadata-plugin/README.md
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/Main.java
  analyzer/pom-analyzer/README.md
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/Main.java
  analyzer/repo-cloner-plugin/README.md
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/Main.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/GitCloner.java
  core/README.md
  server/README.md
Labels: Type: Maintenance

#50 Develop branch workflows
  .github/workflows/dockerpublish_develop.yaml
  .github/workflows/maven_develop.yml
Labels: Type: Maintenance

#51 Improve POM Analyzer
  analyzer/pom-analyzer/pom.xml
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractorTest.java
Labels: enhancement

#44 Improve RepoCloner
  analyzer/repo-cloner-plugin/pom.xml
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPlugin.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/GitCloner.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/HgCloner.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/SvnCloner.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPluginTest.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/utils/GitClonerTest.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/utils/HgClonerTest.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/utils/SvnClonerTest.java
Labels: enhancement

#53 Plugin performance measure
  server/src/main/java/eu/fasten/server/plugins/kafka/FastenKafkaPlugin.java
Labels: enhancement

#46 Improving OPAL
  analyzer/javacg-opal/pom.xml
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/Main.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/CallGraphConstructor.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraph.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/exceptions/EmptyCallGraphException.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/exceptions/OPALException.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/OPALPluginTest.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/CallGraphConstructorTest.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinateTest.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraphTest.java
Labels: maintenance

#49 Delete MetadataDaoTest class
  core/src/test/java/eu/fasten/core/data/metadatadb/MetadataDaoTest.java
Labels: Priority: Low, maintenance

#59 Improve RepoCloner
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/Main.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPlugin.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/GitCloner.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/utils/HgCloner.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPluginTest.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/utils/HgClonerTest.java
Labels: Priority: Medium, maintenance

#63 Switches to fastutils in metadata plugin
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePlugin.java
Labels: Priority: Medium, maintenance

#61 Improve error handling in OPAL plugin
  analyzer/javacg-opal/pom.xml
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/CallGraphConstructor.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinate.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraph.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/MavenCoordinateTest.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/PartialCallGraphTest.java
Labels: maintenance

#64 Fix NullPointerException in OPAL plugin
  analyzer/javacg-opal/pom.xml
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/analysis/OPALClassHierarchy.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/data/analysis/OPALClassHierarchyTest.java
Labels: maintenance

#66 POM Analyzer support for multiple Maven repositories
  analyzer/pom-analyzer/pom.xml
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractorTest.java
Labels: Priority: Medium, enhancement

#67 New callables insertion strategy
  analyzer/metadata-plugin/pom.xml
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePlugin.java
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePluginTest.java
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: Priority: Critical, maintenance
