Repository fasten-project/fasten, pull requests merged in 2021-11, with the labels that each got.

#322 Fix REST API application and container not exiting on error
  .run/Main.run.xml
  analyzer/restapi-plugin/pom.xml
  analyzer/restapi-plugin/src/main/resources/application.properties
Labels: bug

#330 Adding normal/priority message processing to the FASTEN server
  analyzer/callable-index/src/main/java/eu/fasten/analyzer/callableindex/CallableIndexServerPlugin.java
  analyzer/callable-index/src/test/java/eu/fasten/analyzer/callableindex/CallableIndexServerPluginTest.java
  analyzer/dummy-plugin/pom.xml
  analyzer/dummy-plugin/src/main/java/eu/fasten/analyzer/dummyplugin/DummyPlugin.java
  analyzer/dummy-plugin/src/main/java/eu/fasten/analyzer/dummyplugin/Main.java
  analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/OPALPlugin.java
  analyzer/javacg-opal/src/test/java/eu/fasten/analyzer/javacgopal/OPALPluginTest.java
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDBExtension.java
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabaseCPlugin.java
  analyzer/metadata-plugin/src/main/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePythonPlugin.java
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabaseCPluginTest.java
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabaseJavaPluginTest.java
  analyzer/metadata-plugin/src/test/java/eu/fasten/analyzer/metadataplugin/MetadataDatabasePythonPluginTest.java
  analyzer/parallel-vulnerability-cache-invalidation-plugin/src/main/java/eu/fasten/analyzer/parallelvulnerabilitycacheinvalidationplugin/ParallelVulnerabilityCacheInvalidationPlugin.java
  analyzer/parallel-vulnerability-cache-invalidation-plugin/src/test/java/eu/fasten/analyzer/parallelvulnerabilitycacheinvalidationplugin/ParallelVulnerabilityCacheInvalidationPluginTest.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPluginTest.java
  analyzer/pom.xml
  analyzer/quality-analyzer/src/main/java/eu/fasten/analyzer/qualityanalyzer/QualityAnalyzerPlugin.java
  analyzer/quality-analyzer/src/test/java/eu/fasten/analyzer/qualityanalyzer/QualityAnalyzerPluginTest.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/RepoAnalyzerPlugin.java
  analyzer/repo-cloner-plugin/src/main/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPlugin.java
  analyzer/repo-cloner-plugin/src/test/java/eu/fasten/analyzer/repoclonerplugin/RepoClonerPluginTest.java
  analyzer/vulnerability-cache-invalidation-plugin/src/main/java/eu/fasten/analyzer/vulnerabilitycacheinvalidationplugin/VulnerabilityCacheInvalidationPlugin.java
  analyzer/vulnerability-cache-invalidation-plugin/src/test/java/eu/fasten/analyzer/vulnerabilitycacheinvalidationplugin/VulnerabilityCacheInvalidationPluginTest.java
  analyzer/vulnerability-cache-processor-plugin/src/main/java/eu/fasten/analyzer/vulnerabilitycacheprocessorplugin/VulnerabilityCacheProcessorPlugin.java
  analyzer/vulnerability-cache-processor-plugin/src/test/java/eu/fasten/analyzer/vulnerabilitycacheprocessorplugin/VulnerabilityCacheProcessorPluginTest.java
  analyzer/vulnerability-consumer/src/main/java/eu/fasten/analyzer/vulnerabilityconsumer/VulnerabilityConsumer.java
  analyzer/vulnerability-consumer/src/test/java/eu/fasten/vulnerabilityconsumer/VulnerabilityConsumerTest.java
  analyzer/vulnerability-packages-listener/src/main/java/eu/fasten/analyzer/vulnerabilitypackageslistener/VulnerabilityPackagesListener.java
  analyzer/vulnerability-statements-processor/src/main/java/eu/fasten/analyzer/vulnerabilitystatementsprocessor/VulnerabilityStatementsProcessor.java
  analyzer/vulnerability-statements-processor/src/test/java/eu/fasten/vulnerabilitystatementsprocessor/VulnerabilityStatementsProcessorTest.java
  core/src/main/java/eu/fasten/core/plugins/KafkaPlugin.java
  server/src/main/java/eu/fasten/server/FastenServer.java
  server/src/main/java/eu/fasten/server/connectors/KafkaConnector.java
  server/src/main/java/eu/fasten/server/plugins/kafka/FastenKafkaPlugin.java
  server/src/main/java/eu/fasten/server/plugins/kafka/LocalStorage.java
  server/src/test/java/eu/fasten/server/plugins/kafka/KafkaConsumeTimeoutTest.java
  server/src/test/java/eu/fasten/server/plugins/kafka/KafkaPluginConsumeBehaviourTest.java
  server/src/test/java/eu/fasten/server/plugins/kafka/LocalStorageTest.java
Labels: enhancement

#321 Improvements to POMAnalyzer
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/POMAnalyzerPlugin.java
  analyzer/pom-analyzer/src/main/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractor.java
  analyzer/pom-analyzer/src/test/java/eu/fasten/analyzer/pomanalyzer/pom/DataExtractorTest.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/LazyIngestionProvider.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/BinaryModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/CallableApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/DependencyApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/EdgeApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/FileApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/ModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/PackageApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/ResolutionApiServiceImpl.java
  analyzer/restapi-plugin/src/test/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApiTest.java
  analyzer/restapi-plugin/src/test/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/PackageApiServiceImplTest.java
  core/pom.xml
  core/src/main/java/eu/fasten/core/maven/utils/MavenUtilities.java
  core/src/test/java/eu/fasten/core/maven/utils/MavenUtilitiesTest.java
Labels: bug, enhancement

#325 Vulnerability restapi
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/VulnerabilityApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/VulnerabilityApiService.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/VulnerabilityApiServiceImpl.java
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: enhancement
