Repository fasten-project/fasten, pull requests merged in 2021-02, with the labels that each got.

#208 Utility parser for partial FASTEN URI
  core/src/main/java/eu/fasten/core/utils/FastenUriUtils.java
  core/src/test/java/eu/fasten/core/utils/FastenUriUtilsTest.java
Labels: Priority: Medium, enhancement

#219 API: Add module exist check for endpoints
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/BinaryModuleApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/CallableApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/DependencyApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/EdgeApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/FileApiServiceImpl.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/ModuleApiServiceImpl.java
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: Priority: Low, bug

#229 Repo analyzer
  analyzer/pom.xml
  analyzer/repo-analyzer/pom.xml
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/Main.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/RepoAnalyzerPlugin.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/AntRepoAnalyzer.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/BuildManager.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/GradleRepoAnalyzer.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/MavenRepoAnalyzer.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/RepoAnalyzer.java
  analyzer/repo-analyzer/src/main/java/eu/fasten/analyzer/repoanalyzer/repo/RepoAnalyzerFactory.java
  analyzer/repo-analyzer/src/test/java/eu/fasten/analyzer/repoanalyzer/RepoAnalyzerPluginTest.java
  analyzer/repo-analyzer/src/test/java/eu/fasten/analyzer/repoanalyzer/repo/AntRepoAnalyzerTest.java
  analyzer/repo-analyzer/src/test/java/eu/fasten/analyzer/repoanalyzer/repo/GradleRepoAnalyzerTest.java
  analyzer/repo-analyzer/src/test/java/eu/fasten/analyzer/repoanalyzer/repo/MavenRepoAnalyzerTest.java
  analyzer/repo-analyzer/src/test/java/eu/fasten/analyzer/repoanalyzer/repo/RepoAnalyzerTest.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module1/custom/src/main/java/App.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module1/custom/src/main/java/Util.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module1/custom/src/test/java/AppTest.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module1/custom/src/test/java/OtherTest.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module1/pom.xml
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module2/pom.xml
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module2/src/main/java/App.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module2/src/test/java/AnotherAppTest.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/module2/src/test/java/AppTest.java
  analyzer/repo-analyzer/src/test/resources/completeMavenProject/pom.xml
  analyzer/repo-analyzer/src/test/resources/emptyRepo/wrongBuildFile.txt
  analyzer/repo-analyzer/src/test/resources/simpleAntRepo/build.xml
  analyzer/repo-analyzer/src/test/resources/simpleGradleKotlinRepo/build.gradle.kts
  analyzer/repo-analyzer/src/test/resources/simpleGradleKotlinRepo/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleGradleKotlinRepo/subprojects/module1/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleGradleKotlinRepo/subprojects/module2/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleGradleRepo/build.gradle
  analyzer/repo-analyzer/src/test/resources/simpleGradleRepo/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleGradleRepo/subprojects/module1/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleGradleRepo/subprojects/module2/src/App.java
  analyzer/repo-analyzer/src/test/resources/simpleMavenRepo/module1/pom.xml
  analyzer/repo-analyzer/src/test/resources/simpleMavenRepo/module1/submodule1/pom.xml
  analyzer/repo-analyzer/src/test/resources/simpleMavenRepo/module2/pom.xml
  analyzer/repo-analyzer/src/test/resources/simpleMavenRepo/module3/pom.xml
  analyzer/repo-analyzer/src/test/resources/simpleMavenRepo/pom.xml
Labels: enhancement

#228 Reducing the size of the Docker image for FASTEN dev.
  .github/workflows/dockerpublish_develop_slim.yaml
  analyzer/javacg-opal/pom.xml
  docker/slim/Dockerfile
Labels: enhancement, help wanted

#243 Add placeholders in Spring app properties instead of hard-coded values
  analyzer/restapi-plugin/src/main/resources/application.properties
Labels: Priority: Low, maintenance

#244 dbMerge OutOfMemory fix
  core/src/main/java/eu/fasten/core/merge/DatabaseMerger.java
Labels: Priority: High, bug
