Repository fasten-project/fasten, pull requests merged in 2022-06, with the labels that each got.

#465 Stop/restart the Spring app (REST API) if `PSQLException` occurs
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/ExceptionHandling.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/ShutdownManager.java
Labels: enhancement, Priority: High

#467 Make `MavenResolverIO` to create the dependency graph directory if it doesn't exist
  core/src/main/java/eu/fasten/core/maven/resolution/MavenResolverIO.java
Labels: enhancement

#477 Improved callable name matching of the QualityAnalyzer (again).
  analyzer/quality-analyzer/src/main/java/eu/fasten/analyzer/qualityanalyzer/MetadataUtils.java
  analyzer/quality-analyzer/src/test/java/eu/fasten/analyzer/qualityanalyzer/MetadataUtilsTest.java
Labels: bug
