Repository fasten-project/fasten, pull requests merged in 2022-01, with the labels that each got.

#377 Quickfix: package search query for Rest API
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: bug, Priority: Low

#360 Adjust API response to prettify rendering of callables in web
  core/src/main/java/eu/fasten/core/data/metadatadb/MetadataDao.java
Labels: enhancement, Priority: Medium

#386 Quckfix: make VulnCallChainsAPI lazy so init after KnowledgeBaseConne…
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/VulnerableCallChainsApi.java
  analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/VulnerableCallChainsApiServiceImpl.java
Labels: bug, Priority: High

#357 Extended stored error information in FastenKafkaPlugin
  server/src/main/java/eu/fasten/server/plugins/kafka/ExistsInLocalStorageException.java
  server/src/main/java/eu/fasten/server/plugins/kafka/FastenKafkaPlugin.java
  server/src/test/java/eu/fasten/server/plugins/kafka/KafkaPluginConsumeBehaviourTest.java
Labels: enhancement
